### ISSUE TITLE
Upgrading an existing repo?

### ISSUE THREAD

**Issue by floehopper** [actionsflow/actionsflow-workflow-default#2]
I created a repo some time ago based on the template as recommended in the instructions. However, now I'm seeing security vulnerabilities in my repo and I want to include all the latest changes from this repo. Can you recommend a way to do that? I can't seem to re-use the commits from this repo, because my repo has a different git history.

**Comment by theowenyoung** [comment]
Hi, @floehopper , please see https://actionsflow.github.io/docs/upgrade/

**Comment by floehopper** [comment]
Thanks 👍
